### PR TITLE
Add rewrite compatibility for Ebizmarts_Mandrill_Model_Email_Template

### PR DESCRIPTION
**Pull request by SchumacherFM**
Thanks for merging!

### CODE REVIEW

**Comment by jissereitsma** [comment]
Dirty fix (as was my previous add-on) but needed to get things going. Merging ... Many thanks for the addition!

**Comment by SchumacherFM** [comment]
That dirty fix is quite common ...

**Comment by jissereitsma** [comment]
I know I know ;) Only https://github.com/danslo/Danslo_Aop would fix it, but that's too bazuka here.

**Comment by SchumacherFM** [comment]
Danslo_Aop would fix thousands of modules :joy:

**Pull request merged**
